### ISSUE TITLE
Android 对云代码的调用有问题？

### ISSUE THREAD

**Issue by godblesshugh** [leancloud/leantodo-weapp#1]
在 iOS 和模拟器上是没问题的，但是在 Android 中：Android 4.4.2 WeChat 6.3.31.940
query 和 AV.Cloud.run 都无法接到回调。
请求发送成功了，回调没有被触发。

**Comment by godblesshugh** [comment]
#2

**Comment by triplezhao** [comment]
确实有这问题，我也发现了。 在开发工具上没问题。 到真机上请求没反应。 lg g3  5.0系统

**Comment by godblesshugh** [comment]
提了 PR 还没通过
