### ISSUE TITLE
为什么在微信开发者工具里面

### ISSUE THREAD

**Issue by zy308718320** [leancloud/leantodo-weapp#10]
https://app-router.leancloud.cn/1/route?appId=XXXXXXXXXXXXXXXXXXXXXX和https://api.leancloud.cn/1.1/users接口都是超时的，我自己写的代码是有问题的，所以下载了你们这个官方dome一样有问题

**Comment by leeyeh** [comment]
duplicated: https://forum.leancloud.cn/t/av-init/14368

如果是这样的话基本可以认为是你的开发环境有问题。因为按现在提供的信息完全无法复现你的问题，建议提供一个可以复现你的问题的最小完整项目代码。

**Comment by xx19941215** [comment]
1.设置-》不使用任何代理 
2.重启开发者工具
3.enjoy

**Comment by zhhl-xian** [comment]
WAService.js:3 thirdScriptError
userId must be a string.;at "pages/todos/todos" page addTodo function
Error: userId must be a string.
大神帮我看看

**Comment by GuojinTseng** [comment]
我的程序报错
POST https://u9vrl5ml.api.lncld.net/1.1/users 400 ()
大神帮忙看看，谢谢

**Comment by leeyeh** [comment]
@GuojinTseng

请移步论坛，贴一下这个请求的 response body。

**Comment by GuojinTseng** [comment]
我已经在
https://forum.leancloud.cn/t/post-400/17083
里面尽量详细的写了我的操作和问题

我可能不是太明白您所说的response body是什么，如果有不清楚的地方希望您指出

祝好

2018-01-09 21:40 GMT+08:00 Lee Yeh <notifications@github.com>:
