### ISSUE TITLE
似乎不支持wepy？

### ISSUE THREAD

**Issue by beiguancyc** [leancloud/leantodo-weapp#11]
目前在wepy里尝试了下，似乎没出现预料的结果
import av from '../utils/av-weapp-min'

av.init({
      appId: XXX,
      appKey: XXX,
    })
var student= await new av.Query('student')

**Comment by leeyeh** [comment]
这的项目并不是使用 wepy 开发的。

如果遇到了具体的问题，还请详细描述问题。如果你能确认这是 SDK 的问题，请在 SDK 的 repo 中提 issue。如果是 wepy 的问题，请向 wepy 反馈。

谢谢。
