### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by chence** [leancloud/leantodo-weapp#14]
todo.js 里有好几处 `consolo.error`

**Comment by leeyeh** [comment]
具体是什么异常？

**Comment by chence** [comment]
拼写错误啊，应该是`console.error`，您上次的提交这几处写的都是`consolo`
![image](https://user-images.githubusercontent.com/1147261/37147099-bdda2102-2300-11e8-99f4-47ee4ff149be.png)

**Comment by leeyeh** [comment]
非常感谢指出问题。
