### ISSUE TITLE
微信错误，errcode: 40029

### ISSUE THREAD

**Issue by shiweifu** [leancloud/leantodo-weapp#8]
在后台配置了公众平台的 AppID 和 AppSecret，然后在代码中配置了项目的 AppID 和 AppKey，执行的时候显示：

http://ac-HSNl7zbI.clouddn.com/jV2SWbSC6Puv6IzhyrQjmur0rezDOeERf8rfmNjL.jpg

请问这是哪里没搞对？

这个公众平台的账号没有开通小程序，但是已经通过了认证，这个有影响么？

**Comment by leeyeh** [comment]
>这个公众平台的账号没有开通小程序，但是已经通过了认证，这个有影响么？

必须使用小程序的 AppID 和 AppSecret，与公众平台是独立的。
